### ISSUE TITLE
Quelques conseils pour développeur junior

### ISSUE THREAD

**Issue by RudlanL** [tidusia/ama#1]
Bonjour Thibaud, j'ai été diplômé récemment d'une licence professionnelle en développement d'application web, je suis à la recherche de mon premier emploi en tant que développeur JS, PHP ou fullstack. 
Auriez-vous quels conseils à me proposer ? 

J'attends votre réponse avec impatience.

**Comment by tidusia** [comment]
## Contexte

Bonjour, @RudlanL, je vais tenter de répondre au mieux à votre question. Mais je dois aussi rappeler mon contexte : je n'ai jamais eu à chercher de job en tant que dev, car je me suis lancé en autodidacte freelance.

Malgré cela, j'ai une certaine idée de comment fonctionne le marché. Et puis j'ai aussi été salarié quelques mois durant mes 6 années de freelance.

## Une entrée dans le marché souvent difficile

Je vois souvent sur LinkedIn des posts de nouveaux diplômés qui ont du mal à trouver leur premier emploi. Le cercle infernal classique du "Besoin d'expérience pour être recruté, mais besoin d'être recruté pour gagner en expérience" ressort souvent.

Donc si cette phase est difficile, rassurez-vous : ça arrive à énormément de monde de galérer à décrocher leur premier job.

Autre point de réassurance : une fois sur les rails, le métier est quand même très safe et se retrouver ensuite au chômage sera probablement très rare. Il y a beaucoup de demandes de développeurs expérimentés. Tout le défi sera donc d'arriver à ce statut "expérimenté". Et ça, c'est plus facile que ce qu'on pourrait imaginer.

## Ne pas se voiler la face sur la réalité du recrutement

Déjà, je pense que ce ne sont pas forcément les plus qualifiés qui décrochent le plus facilement leur job, et que ce ne sont pas les plus doués en dev qui ont les meilleurs salaires.

Acquérir un bon job et savoir négocier un bon salaire sont des compétences, qu'on pourrait appeler du marketing. En tant que freelance, c'est une compétence critique pour bien en vivre, mais pour un salarié, ça peut faire la différence entre trouver du taf et choper un bon job.

Autre point important : les entreprises recrutent aussi beaucoup par le bouche-à-oreille. Donc c'est important de contacter aussi d'autres personnes dans vos connaissances qui pourraient vous pistonner dans une boite. Il n'y a aucune honte à avoir là-dessus, car le biais est du côté de l'entreprise : il est plus facile de faire confiance à une personne recommandée par quelqu'un en interne qu'à un parfait inconnu. Donc, ne pas hésiter à profiter de cette situation si vous avez du réseau. 


## Gestion du temps

Chercher un boulot, surtout s’il y a un faible taux de réponse et beaucoup de refus, peut vite devenir déprimant.

Il sera de bon ton d'allier l'utile et l'agréable : se faire plaisir avec des projets personnels.

Une bonne organisation sera la clé. Il vaut mieux se focaliser sur le respect d'un emploi du temps efficace avec les bonnes routines que sur des objectifs non contrôlables comme (décrocher 5 rendez-vous cette semaine).
Une idée de planning, entre 9h et 17h : 
- prendre 3 heures pour la recherche d'emploi active (en une traite ou découpé, selon votre gestion de l'énergie)
- prendre 2 heures pour des projets personnels
- prendre une bonne pause à midi avec du sport, essentiel pour garder une bonne énergie
- si possible, faire un peu de veille / écouter du podcast (pourquoi pas pendant le sport) / lire des livres techniques

En gros, un rythme efficace et soutenable, que vous pourriez imaginer reproduire une fois recruté (en remplaçant les heures de recherche/projet perso par le boulot).

Votre travail actuellement, c'est de se faire recruter, et il faut vraiment le voir comme un travail salarié, avec la discipline et la séparation avec la vie privée qui va avec


## Conseils en vrac

- Soyez précis sur ce que vous cherchez comme job. C'est très dur pour un recruteur de se projeter sur un post du type : "recherche CDI développeur web, je suis junior en Drupal, React, WordPress, Angular, Svelte, Devops, fullstack, réparation de machine à café, et expert en papotage autour de cette dernière". Je grossis bien entendu le trait, mais ce genre de présentation fait plus peur qu'autre chose. Qu'est-ce qui vous a le plus plu dans votre formation ? Drupal ? OK alors continuez d'apprendre dans cette techno, faites vos projets perso avec, et mettez en avant du contenu et une recherche accès dessus, ça maximisera vos chances. Attention ! Je pense qu'une certaine diversité dans son savoir est une bonne chose, mais pour décrocher un job ou des missions, se focaliser sur une techno, ça rapporte plus de cash.
- Parlez-en à tout le monde, vraiment. Même à la baby-sitter de votre voisine. On sait jamais, la puissance du bouche-à-oreille a quelque chose de magique et autant son oncle à cette baby-sitter cherche justement quelqu'un et n'a pas l'argent pour payer des recruteurs sur LinkedIn.
- Pour savoir sur quel projet personnel se lancer : tentez d'allier le dev à une passion (si possible en utilisant une techno ou un langage que vous souhaitez mettre en avant. N'allez par pitié pas recréer un énième Trello bidon que vous n'utiliserez jamais. Perso, j'aime créer du contenu quand j'ai du temps, et aider les autres, mais si j'avais plus de temps, je serais contributeur sur un logiciel de jeu de rôle nommé FoundryVTT. Ça serait pour moi un excellent de continuer à apprendre, montrer que je sais collaborer et être actif tout en prenant mon pied, car je suis passionné par le jeu de rôle. Il y a aussi cet [article de Je Suis Un Dev](https://www.jesuisundev.com/projet-perso/) qui parle mieux que moi de ce sujet.
- Pour ce qui est du détail (CV, lettre de motivation, etc), je fais du hors-piste. Je n'ai pas de CV, car freelance, et les rares fois où j'ai fait une lettre de motivation, c'était quasiment du marketing pur, que j'ai appris via des formations payantes et en lisant des articles de blog. Je ne suis pas certain que mon approche fasse l'affaire pour un premier job.
- Il y a des gens bien [chez WeLoveDevs](https://welovedevs.com/fr/) je pense que vous devriez y faire un tour. Il y a aussi un blog de qualité.

**Comment by tidusia** [comment]
Je viens aussi de copier cette réponse sur mon second cerveau public : https://thibaud-duthoit.notion.site/Quelques-conseils-pour-d-veloppeur-junior-452426cfe64f4ce6b23bf59a5e8a3c59

Il est possible d'y trouver d'autres éléments intéressants dans des domaines très variés. En tout cas ma façon de voir les choses !
